language: python
python:
- 2.7
- 3.5
- 3.6
- 3.7
- 3.8
sudo: false
cache:
  directories:
  - eggs
install:
- pip install -U setuptools zc.buildout
- buildout -N -t 3 install test code-analysis
script:
- bin/test
- bin/code-analysis
